#include <stdlib.h>
#include <ctype.h>

#include "../gwnum.h"
#include "../gwtables.h"
#include "../gwnum_func.h"
#include "../gwcommon.h"
#include "../unravel.h"
#include "../xarch.h"
#include "../xmult.h"
#include "../xbasics.h"
#include "xnormal.h"
#include "xmult3a.h"

inorm(xr3s4, noexec, noexec, noexec, exec, exec)
inorm(xr3es4, noexec, exec, noexec, exec, exec)
inorm(xr3cs4, noexec, noexec, exec, exec, exec)
inorm(xr3ecs4, noexec, exec, exec, exec, exec)
inorm(xi3s4, exec, noexec, noexec, exec, exec)
inorm(xi3es4, exec, exec, noexec, exec, exec)
inorm(xi3cs4, exec, noexec, exec, exec, exec)
inorm(xi3ecs4, exec, exec, exec, exec, exec)
zpnorm(xr3zps4, noexec, noexec, noexec, exec, exec, exec, noexec, noexec)
zpnorm(xr3zps4c1, noexec, noexec, noexec, exec, exec, exec, exec, noexec)
zpnorm(xr3zps4cm1, noexec, noexec, noexec, exec, exec, exec, noexec, exec)
zpnorm(xr3zpes4, noexec, exec, noexec, exec, exec, exec, noexec, noexec)
zpnorm(xr3zpes4c1, noexec, exec, noexec, exec, exec, exec, exec, noexec)
zpnorm(xr3zpes4cm1, noexec, exec, noexec, exec, exec, exec, noexec, exec)
zpnorm(xr3zpcs4, noexec, noexec, exec, exec, exec, exec, noexec, noexec)
zpnorm(xr3zpecs4, noexec, exec, exec, exec, exec, exec, noexec, noexec)
zpnorm(xi3zps4, exec, noexec, noexec, exec, exec, exec, noexec, noexec)
zpnorm(xi3zps4c1, exec, noexec, noexec, exec, exec, exec, exec, noexec)
zpnorm(xi3zps4cm1, exec, noexec, noexec, exec, exec, exec, noexec, exec)
zpnorm(xi3zpes4, exec, exec, noexec, exec, exec, exec, noexec, noexec)
zpnorm(xi3zpes4c1, exec, exec, noexec, exec, exec, exec, exec, noexec)
zpnorm(xi3zpes4cm1, exec, exec, noexec, exec, exec, exec, noexec, exec)
zpnorm(xi3zpcs4, exec, noexec, exec, exec, exec, exec, noexec, noexec)
zpnorm(xi3zpecs4, exec, exec, exec, exec, exec, exec, noexec, noexec)
zpnorm(xr3zps4k, noexec, noexec, noexec, exec, exec, noexec, noexec, noexec)
zpnorm(xr3zps4kc1, noexec, noexec, noexec, exec, exec, noexec, exec, noexec)
zpnorm(xr3zps4kcm1, noexec, noexec, noexec, exec, exec, noexec, noexec, exec)
zpnorm(xr3zpes4k, noexec, exec, noexec, exec, exec, noexec, noexec, noexec)
zpnorm(xr3zpes4kc1, noexec, exec, noexec, exec, exec, noexec, exec, noexec)
zpnorm(xr3zpes4kcm1, noexec, exec, noexec, exec, exec, noexec, noexec, exec)
zpnorm(xr3zpcs4k, noexec, noexec, exec, exec, exec, noexec, noexec, noexec)
zpnorm(xr3zpecs4k, noexec, exec, exec, exec, exec, noexec, noexec, noexec)
zpnorm(xi3zps4k, exec, noexec, noexec, exec, exec, noexec, noexec, noexec)
zpnorm(xi3zps4kc1, exec, noexec, noexec, exec, exec, noexec, exec, noexec)
zpnorm(xi3zps4kcm1, exec, noexec, noexec, exec, exec, noexec, noexec, exec)
zpnorm(xi3zpes4k, exec, exec, noexec, exec, exec, noexec, noexec, noexec)
zpnorm(xi3zpes4kc1, exec, exec, noexec, exec, exec, noexec, exec, noexec)
zpnorm(xi3zpes4kcm1, exec, exec, noexec, exec, exec, noexec, noexec, exec)
zpnorm(xi3zpcs4k, exec, noexec, exec, exec, exec, noexec, noexec, noexec)
zpnorm(xi3zpecs4k, exec, exec, exec, exec, exec, noexec, noexec, noexec)

inorm(xr3bs4, noexec, noexec, noexec, noexec, exec)
inorm(xr3ebs4, noexec, exec, noexec, noexec, exec)
inorm(xr3cbs4, noexec, noexec, exec, noexec, exec)
inorm(xr3ecbs4, noexec, exec, exec, noexec, exec)
inorm(xi3bs4, exec, noexec, noexec, noexec, exec)
inorm(xi3ebs4, exec, exec, noexec, noexec, exec)
inorm(xi3cbs4, exec, noexec, exec, noexec, exec)
inorm(xi3ecbs4, exec, exec, exec, noexec, exec)
zpnorm(xr3zpbs4, noexec, noexec, noexec, noexec, exec, exec, noexec, noexec)
zpnorm(xr3zpbs4c1, noexec, noexec, noexec, noexec, exec, exec, exec, noexec)
zpnorm(xr3zpbs4cm1, noexec, noexec, noexec, noexec, exec, exec, noexec, exec)
zpnorm(xr3zpebs4, noexec, exec, noexec, noexec, exec, exec, noexec, noexec)
zpnorm(xr3zpebs4c1, noexec, exec, noexec, noexec, exec, exec, exec, noexec)
zpnorm(xr3zpebs4cm1, noexec, exec, noexec, noexec, exec, exec, noexec, exec)
zpnorm(xr3zpcbs4, noexec, noexec, exec, noexec, exec, exec, noexec, noexec)
zpnorm(xr3zpecbs4, noexec, exec, exec, noexec, exec, exec, noexec, noexec)
zpnorm(xi3zpbs4, exec, noexec, noexec, noexec, exec, exec, noexec, noexec)
zpnorm(xi3zpbs4c1, exec, noexec, noexec, noexec, exec, exec, exec, noexec)
zpnorm(xi3zpbs4cm1, exec, noexec, noexec, noexec, exec, exec, noexec, exec)
zpnorm(xi3zpebs4, exec, exec, noexec, noexec, exec, exec, noexec, noexec)
zpnorm(xi3zpebs4c1, exec, exec, noexec, noexec, exec, exec, exec, noexec)
zpnorm(xi3zpebs4cm1, exec, exec, noexec, noexec, exec, exec, noexec, exec)
zpnorm(xi3zpcbs4, exec, noexec, exec, noexec, exec, exec, noexec, noexec)
zpnorm(xi3zpecbs4, exec, exec, exec, noexec, exec, exec, noexec, noexec)
zpnorm(xr3zpbs4k, noexec, noexec, noexec, noexec, exec, noexec, noexec, noexec)
zpnorm(xr3zpbs4kc1, noexec, noexec, noexec, noexec, exec, noexec, exec, noexec)
zpnorm(xr3zpbs4kcm1, noexec, noexec, noexec, noexec, exec, noexec, noexec, exec)
zpnorm(xr3zpebs4k, noexec, exec, noexec, noexec, exec, noexec, noexec, noexec)
zpnorm(xr3zpebs4kc1, noexec, exec, noexec, noexec, exec, noexec, exec, noexec)
zpnorm(xr3zpebs4kcm1, noexec, exec, noexec, noexec, exec, noexec, noexec, exec)
zpnorm(xr3zpcbs4k, noexec, noexec, exec, noexec, exec, noexec, noexec, noexec)
zpnorm(xr3zpecbs4k, noexec, exec, exec, noexec, exec, noexec, noexec, noexec)
zpnorm(xi3zpbs4k, exec, noexec, noexec, noexec, exec, noexec, noexec, noexec)
zpnorm(xi3zpbs4kc1, exec, noexec, noexec, noexec, exec, noexec, exec, noexec)
zpnorm(xi3zpbs4kcm1, exec, noexec, noexec, noexec, exec, noexec, noexec, exec)
zpnorm(xi3zpebs4k, exec, exec, noexec, noexec, exec, noexec, noexec, noexec)
zpnorm(xi3zpebs4kc1, exec, exec, noexec, noexec, exec, noexec, exec, noexec)
zpnorm(xi3zpebs4kcm1, exec, exec, noexec, noexec, exec, noexec, noexec, exec)
zpnorm(xi3zpcbs4k, exec, noexec, exec, noexec, exec, noexec, noexec, noexec)
zpnorm(xi3zpecbs4k, exec, exec, exec, noexec, exec, noexec, noexec, noexec)
