#include <stdlib.h>
#include <ctype.h>

#include "../gwnum.h"
#include "../gwtables.h"
#include "../gwnum_func.h"
#include "../gwcommon.h"
#include "../unravel.h"
#include "../xarch.h"
#include "../xmult.h"
#include "../xbasics.h"
#include "xnormal.h"
#include "xmult3a.h"

inorm(xr3, noexec, noexec, noexec, exec, noexec)
inorm(xr3e, noexec, exec, noexec, exec, noexec)
inorm(xr3c, noexec, noexec, exec, exec, noexec)
inorm(xr3ec, noexec, exec, exec, exec, noexec)
inorm(xi3, exec, noexec, noexec, exec, noexec)
inorm(xi3e, exec, exec, noexec, exec, noexec)
inorm(xi3c, exec, noexec, exec, exec, noexec)
inorm(xi3ec, exec, exec, exec, exec, noexec)
zpnorm(xr3zp, noexec, noexec, noexec, exec, noexec, exec, noexec, noexec)
zpnorm(xr3zpc1, noexec, noexec, noexec, exec, noexec, exec, exec, noexec)
zpnorm(xr3zpcm1, noexec, noexec, noexec, exec, noexec, exec, noexec, exec)
zpnorm(xr3zpe, noexec, exec, noexec, exec, noexec, exec, noexec, noexec)
zpnorm(xr3zpec1, noexec, exec, noexec, exec, noexec, exec, exec, noexec)
zpnorm(xr3zpecm1, noexec, exec, noexec, exec, noexec, exec, noexec, exec)
zpnorm(xr3zpc, noexec, noexec, exec, exec, noexec, exec, noexec, noexec)
zpnorm(xr3zpec, noexec, exec, exec, exec, noexec, exec, noexec, noexec)
zpnorm(xi3zp, exec, noexec, noexec, exec, noexec, exec, noexec, noexec)
zpnorm(xi3zpc1, exec, noexec, noexec, exec, noexec, exec, exec, noexec)
zpnorm(xi3zpcm1, exec, noexec, noexec, exec, noexec, exec, noexec, exec)
zpnorm(xi3zpe, exec, exec, noexec, exec, noexec, exec, noexec, noexec)
zpnorm(xi3zpec1, exec, exec, noexec, exec, noexec, exec, exec, noexec)
zpnorm(xi3zpecm1, exec, exec, noexec, exec, noexec, exec, noexec, exec)
zpnorm(xi3zpc, exec, noexec, exec, exec, noexec, exec, noexec, noexec)
zpnorm(xi3zpec, exec, exec, exec, exec, noexec, exec, noexec, noexec)
zpnorm(xr3zpk, noexec, noexec, noexec, exec, noexec, noexec, noexec, noexec)
zpnorm(xr3zpkc1, noexec, noexec, noexec, exec, noexec, noexec, exec, noexec)
zpnorm(xr3zpkcm1, noexec, noexec, noexec, exec, noexec, noexec, noexec, exec)
zpnorm(xr3zpek, noexec, exec, noexec, exec, noexec, noexec, noexec, noexec)
zpnorm(xr3zpekc1, noexec, exec, noexec, exec, noexec, noexec, exec, noexec)
zpnorm(xr3zpekcm1, noexec, exec, noexec, exec, noexec, noexec, noexec, exec)
zpnorm(xr3zpck, noexec, noexec, exec, exec, noexec, noexec, noexec, noexec)
zpnorm(xr3zpeck, noexec, exec, exec, exec, noexec, noexec, noexec, noexec)
zpnorm(xi3zpk, exec, noexec, noexec, exec, noexec, noexec, noexec, noexec)
zpnorm(xi3zpkc1, exec, noexec, noexec, exec, noexec, noexec, exec, noexec)
zpnorm(xi3zpkcm1, exec, noexec, noexec, exec, noexec, noexec, noexec, exec)
zpnorm(xi3zpek, exec, exec, noexec, exec, noexec, noexec, noexec, noexec)
zpnorm(xi3zpekc1, exec, exec, noexec, exec, noexec, noexec, exec, noexec)
zpnorm(xi3zpekcm1, exec, exec, noexec, exec, noexec, noexec, noexec, exec)
zpnorm(xi3zpck, exec, noexec, exec, exec, noexec, noexec, noexec, noexec)
zpnorm(xi3zpeck, exec, exec, exec, exec, noexec, noexec, noexec, noexec)

inorm(xr3b, noexec, noexec, noexec, noexec, noexec)
inorm(xr3eb, noexec, exec, noexec, noexec, noexec)
inorm(xr3cb, noexec, noexec, exec, noexec, noexec)
inorm(xr3ecb, noexec, exec, exec, noexec, noexec)
inorm(xi3b, exec, noexec, noexec, noexec, noexec)
inorm(xi3eb, exec, exec, noexec, noexec, noexec)
inorm(xi3cb, exec, noexec, exec, noexec, noexec)
inorm(xi3ecb, exec, exec, exec, noexec, noexec)
zpnorm(xr3zpb, noexec, noexec, noexec, noexec, noexec, exec, noexec, noexec)
zpnorm(xr3zpbc1, noexec, noexec, noexec, noexec, noexec, exec, exec, noexec)
zpnorm(xr3zpbcm1, noexec, noexec, noexec, noexec, noexec, exec, noexec, exec)
zpnorm(xr3zpeb, noexec, exec, noexec, noexec, noexec, exec, noexec, noexec)
zpnorm(xr3zpebc1, noexec, exec, noexec, noexec, noexec, exec, exec, noexec)
zpnorm(xr3zpebcm1, noexec, exec, noexec, noexec, noexec, exec, noexec, exec)
zpnorm(xr3zpcb, noexec, noexec, exec, noexec, noexec, exec, noexec, noexec)
zpnorm(xr3zpecb, noexec, exec, exec, noexec, noexec, exec, noexec, noexec)
zpnorm(xi3zpb, exec, noexec, noexec, noexec, noexec, exec, noexec, noexec)
zpnorm(xi3zpbc1, exec, noexec, noexec, noexec, noexec, exec, exec, noexec)
zpnorm(xi3zpbcm1, exec, noexec, noexec, noexec, noexec, exec, noexec, exec)
zpnorm(xi3zpeb, exec, exec, noexec, noexec, noexec, exec, noexec, noexec)
zpnorm(xi3zpebc1, exec, exec, noexec, noexec, noexec, exec, exec, noexec)
zpnorm(xi3zpebcm1, exec, exec, noexec, noexec, noexec, exec, noexec, exec)
zpnorm(xi3zpcb, exec, noexec, exec, noexec, noexec, exec, noexec, noexec)
zpnorm(xi3zpecb, exec, exec, exec, noexec, noexec, exec, noexec, noexec)
zpnorm(xr3zpbk, noexec, noexec, noexec, noexec, noexec, noexec, noexec, noexec)
zpnorm(xr3zpbkc1, noexec, noexec, noexec, noexec, noexec, noexec, exec, noexec)
zpnorm(xr3zpbkcm1, noexec, noexec, noexec, noexec, noexec, noexec, noexec, exec)
zpnorm(xr3zpebk, noexec, exec, noexec, noexec, noexec, noexec, noexec, noexec)
zpnorm(xr3zpebkc1, noexec, exec, noexec, noexec, noexec, noexec, exec, noexec)
zpnorm(xr3zpebkcm1, noexec, exec, noexec, noexec, noexec, noexec, noexec, exec)
zpnorm(xr3zpcbk, noexec, noexec, exec, noexec, noexec, noexec, noexec, noexec)
zpnorm(xr3zpecbk, noexec, exec, exec, noexec, noexec, noexec, noexec, noexec)
zpnorm(xi3zpbk, exec, noexec, noexec, noexec, noexec, noexec, noexec, noexec)
zpnorm(xi3zpbkc1, exec, noexec, noexec, noexec, noexec, noexec, exec, noexec)
zpnorm(xi3zpbkcm1, exec, noexec, noexec, noexec, noexec, noexec, noexec, exec)
zpnorm(xi3zpebk, exec, exec, noexec, noexec, noexec, noexec, noexec, noexec)
zpnorm(xi3zpebkc1, exec, exec, noexec, noexec, noexec, noexec, exec, noexec)
zpnorm(xi3zpebkcm1, exec, exec, noexec, noexec, noexec, noexec, noexec, exec)
zpnorm(xi3zpcbk, exec, noexec, exec, noexec, noexec, noexec, noexec, noexec)
zpnorm(xi3zpecbk, exec, exec, exec, noexec, noexec, noexec, noexec, noexec)
