#include <stdlib.h>
#include <ctype.h>

#include "../gwnum.h"
#include "../gwtables.h"
#include "../gwnum_func.h"
#include "../gwcommon.h"
#include "../unravel.h"
#include "../xarch.h"
#include "../xbasics.h"
#include "xnormal.h"

#include "xmult1a.h"

inorm(xr1s4, noexec, noexec, noexec, exec, exec)
inorm(xr1es4, noexec, exec, noexec, exec, exec)
inorm(xr1cs4, noexec, noexec, exec, exec, exec)
inorm(xr1ecs4, noexec, exec, exec, exec, exec)
inorm(xi1s4, exec, noexec, noexec, exec, exec)
inorm(xi1es4, exec, exec, noexec, exec, exec)
inorm(xi1cs4, exec, noexec, exec, exec, exec)
inorm(xi1ecs4, exec, exec, exec, exec, exec)
zpnorm(xr1zps4, noexec, noexec, noexec, exec, exec, exec, noexec, noexec)
zpnorm(xr1zps4c1, noexec, noexec, noexec, exec, exec, exec, exec, noexec)
zpnorm(xr1zps4cm1, noexec, noexec, noexec, exec, exec, exec, noexec, exec)
zpnorm(xr1zpes4, noexec, exec, noexec, exec, exec, exec, noexec, noexec)
zpnorm(xr1zpes4c1, noexec, exec, noexec, exec, exec, exec, exec, noexec)
zpnorm(xr1zpes4cm1, noexec, exec, noexec, exec, exec, exec, noexec, exec)
zpnorm(xr1zpcs4, noexec, noexec, exec, exec, exec, exec, noexec, noexec)
zpnorm(xr1zpecs4, noexec, exec, exec, exec, exec, exec, noexec, noexec)
zpnorm(xi1zps4, exec, noexec, noexec, exec, exec, exec, noexec, noexec)
zpnorm(xi1zps4c1, exec, noexec, noexec, exec, exec, exec, exec, noexec)
zpnorm(xi1zps4cm1, exec, noexec, noexec, exec, exec, exec, noexec, exec)
zpnorm(xi1zpes4, exec, exec, noexec, exec, exec, exec, noexec, noexec)
zpnorm(xi1zpes4c1, exec, exec, noexec, exec, exec, exec, exec, noexec)
zpnorm(xi1zpes4cm1, exec, exec, noexec, exec, exec, exec, noexec, exec)
zpnorm(xi1zpcs4, exec, noexec, exec, exec, exec, exec, noexec, noexec)
zpnorm(xi1zpecs4, exec, exec, exec, exec, exec, exec, noexec, noexec)
zpnorm(xr1zps4k, noexec, noexec, noexec, exec, exec, noexec, noexec, noexec)
zpnorm(xr1zps4kc1, noexec, noexec, noexec, exec, exec, noexec, exec, noexec)
zpnorm(xr1zps4kcm1, noexec, noexec, noexec, exec, exec, noexec, noexec, exec)
zpnorm(xr1zpes4k, noexec, exec, noexec, exec, exec, noexec, noexec, noexec)
zpnorm(xr1zpes4kc1, noexec, exec, noexec, exec, exec, noexec, exec, noexec)
zpnorm(xr1zpes4kcm1, noexec, exec, noexec, exec, exec, noexec, noexec, exec)
zpnorm(xr1zpcs4k, noexec, noexec, exec, exec, exec, noexec, noexec, noexec)
zpnorm(xr1zpecs4k, noexec, exec, exec, exec, exec, noexec, noexec, noexec)
zpnorm(xi1zps4k, exec, noexec, noexec, exec, exec, noexec, noexec, noexec)
zpnorm(xi1zps4kc1, exec, noexec, noexec, exec, exec, noexec, exec, noexec)
zpnorm(xi1zps4kcm1, exec, noexec, noexec, exec, exec, noexec, noexec, exec)
zpnorm(xi1zpes4k, exec, exec, noexec, exec, exec, noexec, noexec, noexec)
zpnorm(xi1zpes4kc1, exec, exec, noexec, exec, exec, noexec, exec, noexec)
zpnorm(xi1zpes4kcm1, exec, exec, noexec, exec, exec, noexec, noexec, exec)
zpnorm(xi1zpcs4k, exec, noexec, exec, exec, exec, noexec, noexec, noexec)
zpnorm(xi1zpecs4k, exec, exec, exec, exec, exec, noexec, noexec, noexec)

inorm(xr1bs4, noexec, noexec, noexec, noexec, exec)
inorm(xr1ebs4, noexec, exec, noexec, noexec, exec)
inorm(xr1cbs4, noexec, noexec, exec, noexec, exec)
inorm(xr1ecbs4, noexec, exec, exec, noexec, exec)
inorm(xi1bs4, exec, noexec, noexec, noexec, exec)
inorm(xi1ebs4, exec, exec, noexec, noexec, exec)
inorm(xi1cbs4, exec, noexec, exec, noexec, exec)
inorm(xi1ecbs4, exec, exec, exec, noexec, exec)
zpnorm(xr1zpbs4, noexec, noexec, noexec, noexec, exec, exec, noexec, noexec)
zpnorm(xr1zpbs4c1, noexec, noexec, noexec, noexec, exec, exec, exec, noexec)
zpnorm(xr1zpbs4cm1, noexec, noexec, noexec, noexec, exec, exec, noexec, exec)
zpnorm(xr1zpebs4, noexec, exec, noexec, noexec, exec, exec, noexec, noexec)
zpnorm(xr1zpebs4c1, noexec, exec, noexec, noexec, exec, exec, exec, noexec)
zpnorm(xr1zpebs4cm1, noexec, exec, noexec, noexec, exec, exec, noexec, exec)
zpnorm(xr1zpcbs4, noexec, noexec, exec, noexec, exec, exec, noexec, noexec)
zpnorm(xr1zpecbs4, noexec, exec, exec, noexec, exec, exec, noexec, noexec)
zpnorm(xi1zpbs4, exec, noexec, noexec, noexec, exec, exec, noexec, noexec)
zpnorm(xi1zpbs4c1, exec, noexec, noexec, noexec, exec, exec, exec, noexec)
zpnorm(xi1zpbs4cm1, exec, noexec, noexec, noexec, exec, exec, noexec, exec)
zpnorm(xi1zpebs4, exec, exec, noexec, noexec, exec, exec, noexec, noexec)
zpnorm(xi1zpebs4c1, exec, exec, noexec, noexec, exec, exec, exec, noexec)
zpnorm(xi1zpebs4cm1, exec, exec, noexec, noexec, exec, exec, noexec, exec)
zpnorm(xi1zpcbs4, exec, noexec, exec, noexec, exec, exec, noexec, noexec)
zpnorm(xi1zpecbs4, exec, exec, exec, noexec, exec, exec, noexec, noexec)
zpnorm(xr1zpbs4k, noexec, noexec, noexec, noexec, exec, noexec, noexec, noexec)
zpnorm(xr1zpbs4kc1, noexec, noexec, noexec, noexec, exec, noexec, exec, noexec)
zpnorm(xr1zpbs4kcm1, noexec, noexec, noexec, noexec, exec, noexec, noexec, exec)
zpnorm(xr1zpebs4k, noexec, exec, noexec, noexec, exec, noexec, noexec, noexec)
zpnorm(xr1zpebs4kc1, noexec, exec, noexec, noexec, exec, noexec, exec, noexec)
zpnorm(xr1zpebs4kcm1, noexec, exec, noexec, noexec, exec, noexec, noexec, exec)
zpnorm(xr1zpcbs4k, noexec, noexec, exec, noexec, exec, noexec, noexec, noexec)
zpnorm(xr1zpecbs4k, noexec, exec, exec, noexec, exec, noexec, noexec, noexec)
zpnorm(xi1zpbs4k, exec, noexec, noexec, noexec, exec, noexec, noexec, noexec)
zpnorm(xi1zpbs4kc1, exec, noexec, noexec, noexec, exec, noexec, exec, noexec)
zpnorm(xi1zpbs4kcm1, exec, noexec, noexec, noexec, exec, noexec, noexec, exec)
zpnorm(xi1zpebs4k, exec, exec, noexec, noexec, exec, noexec, noexec, noexec)
zpnorm(xi1zpebs4kc1, exec, exec, noexec, noexec, exec, noexec, exec, noexec)
zpnorm(xi1zpebs4kcm1, exec, exec, noexec, noexec, exec, noexec, noexec, exec)
zpnorm(xi1zpcbs4k, exec, noexec, exec, noexec, exec, noexec, noexec, noexec)
zpnorm(xi1zpecbs4k, exec, exec, exec, noexec, exec, noexec, noexec, noexec)

