#include <stdlib.h>
#include <ctype.h>

#include "../gwnum.h"
#include "../gwcommon.h"
#include "../unravel.h"
#include "../gwtables.h"
#include "../xarch.h"
#include "../xbasics.h"
#include "xnormal.h"

#include "xmult2a.h"

inorm(xr2, noexec, noexec, noexec, noexec, exec, noexec)
inorm(xr2e, noexec, noexec, exec, noexec, exec, noexec)
inorm(xr2c, noexec, noexec, noexec, exec, exec, noexec)
inorm(xr2ec, noexec, noexec, exec, exec, exec, noexec)
inorm(xr2z, noexec, exec, noexec, noexec, exec, noexec)
inorm(xr2ze, noexec, exec, exec, noexec, exec, noexec)
inorm(xi2, exec, noexec, noexec, noexec, exec, noexec)
inorm(xi2e, exec, noexec, exec, noexec, exec, noexec)
inorm(xi2c, exec, noexec, noexec, exec, exec, noexec)
inorm(xi2ec, exec, noexec, exec, exec, exec, noexec)
inorm(xi2z, exec, exec, noexec, noexec, exec, noexec)
inorm(xi2ze, exec, exec, exec, noexec, exec, noexec)
zpnorm(xr2zp, noexec, noexec, noexec, exec, noexec, exec, noexec, noexec)
zpnorm(xr2zpc1, noexec, noexec, noexec, exec, noexec, exec, exec, noexec)
zpnorm(xr2zpcm1, noexec, noexec, noexec, exec, noexec, exec, noexec, exec)
zpnorm(xr2zpe, noexec, exec, noexec, exec, noexec, exec, noexec, noexec)
zpnorm(xr2zpec1, noexec, exec, noexec, exec, noexec, exec, exec, noexec)
zpnorm(xr2zpecm1, noexec, exec, noexec, exec, noexec, exec, noexec, exec)
zpnorm(xr2zpc, noexec, noexec, exec, exec, noexec, exec, noexec, noexec)
zpnorm(xr2zpec, noexec, exec, exec, exec, noexec, exec, noexec, noexec)
zpnorm(xi2zp, exec, noexec, noexec, exec, noexec, exec, noexec, noexec)
zpnorm(xi2zpc1, exec, noexec, noexec, exec, noexec, exec, exec, noexec)
zpnorm(xi2zpcm1, exec, noexec, noexec, exec, noexec, exec, noexec, exec)
zpnorm(xi2zpe, exec, exec, noexec, exec, noexec, exec, noexec, noexec)
zpnorm(xi2zpec1, exec, exec, noexec, exec, noexec, exec, exec, noexec)
zpnorm(xi2zpecm1, exec, exec, noexec, exec, noexec, exec, noexec, exec)
zpnorm(xi2zpc, exec, noexec, exec, exec, noexec, exec, noexec, noexec)
zpnorm(xi2zpec, exec, exec, exec, exec, noexec, exec, noexec, noexec)
zpnorm(xr2zpk, noexec, noexec, noexec, exec, noexec, noexec, noexec, noexec)
zpnorm(xr2zpkc1, noexec, noexec, noexec, exec, noexec, noexec, exec, noexec)
zpnorm(xr2zpkcm1, noexec, noexec, noexec, exec, noexec, noexec, noexec, exec)
zpnorm(xr2zpek, noexec, exec, noexec, exec, noexec, noexec, noexec, noexec)
zpnorm(xr2zpekc1, noexec, exec, noexec, exec, noexec, noexec, exec, noexec)
zpnorm(xr2zpekcm1, noexec, exec, noexec, exec, noexec, noexec, noexec, exec)
zpnorm(xr2zpck, noexec, noexec, exec, exec, noexec, noexec, noexec, noexec)
zpnorm(xr2zpeck, noexec, exec, exec, exec, noexec, noexec, noexec, noexec)
zpnorm(xi2zpk, exec, noexec, noexec, exec, noexec, noexec, noexec, noexec)
zpnorm(xi2zpkc1, exec, noexec, noexec, exec, noexec, noexec, exec, noexec)
zpnorm(xi2zpkcm1, exec, noexec, noexec, exec, noexec, noexec, noexec, exec)
zpnorm(xi2zpek, exec, exec, noexec, exec, noexec, noexec, noexec, noexec)
zpnorm(xi2zpekc1, exec, exec, noexec, exec, noexec, noexec, exec, noexec)
zpnorm(xi2zpekcm1, exec, exec, noexec, exec, noexec, noexec, noexec, exec)
zpnorm(xi2zpck, exec, noexec, exec, exec, noexec, noexec, noexec, noexec)
zpnorm(xi2zpeck, exec, exec, exec, exec, noexec, noexec, noexec, noexec)

inorm(xr2b, noexec, noexec, noexec, noexec, noexec, noexec)
inorm(xr2eb, noexec, noexec, exec, noexec, noexec, noexec)
inorm(xr2cb, noexec, noexec, noexec, exec, noexec, noexec)
inorm(xr2ecb, noexec, noexec, exec, exec, noexec, noexec)
inorm(xi2b, exec, noexec, noexec, noexec, noexec, noexec)
inorm(xi2eb, exec, noexec, exec, noexec, noexec, noexec)
inorm(xi2cb, exec, noexec, noexec, exec, noexec, noexec)
inorm(xi2ecb, exec, noexec, exec, exec, noexec, noexec)
zpnorm(xr2zpb, noexec, noexec, noexec, noexec, noexec, exec, noexec, noexec)
zpnorm(xr2zpbc1, noexec, noexec, noexec, noexec, noexec, exec, exec, noexec)
zpnorm(xr2zpbcm1, noexec, noexec, noexec, noexec, noexec, exec, noexec, exec)
zpnorm(xr2zpeb, noexec, exec, noexec, noexec, noexec, exec, noexec, noexec)
zpnorm(xr2zpebc1, noexec, exec, noexec, noexec, noexec, exec, exec, noexec)
zpnorm(xr2zpebcm1, noexec, exec, noexec, noexec, noexec, exec, noexec, exec)
zpnorm(xr2zpcb, noexec, noexec, exec, noexec, noexec, exec, noexec, noexec)
zpnorm(xr2zpecb, noexec, exec, exec, noexec, noexec, exec, noexec, noexec)
zpnorm(xi2zpb, exec, noexec, noexec, noexec, noexec, exec, noexec, noexec)
zpnorm(xi2zpbc1, exec, noexec, noexec, noexec, noexec, exec, exec, noexec)
zpnorm(xi2zpbcm1, exec, noexec, noexec, noexec, noexec, exec, noexec, exec)
zpnorm(xi2zpeb, exec, exec, noexec, noexec, noexec, exec, noexec, noexec)
zpnorm(xi2zpebc1, exec, exec, noexec, noexec, noexec, exec, exec, noexec)
zpnorm(xi2zpebcm1, exec, exec, noexec, noexec, noexec, exec, noexec, exec)
zpnorm(xi2zpcb, exec, noexec, exec, noexec, noexec, exec, noexec, noexec)
zpnorm(xi2zpecb, exec, exec, exec, noexec, noexec, exec, noexec, noexec)
zpnorm(xr2zpbk, noexec, noexec, noexec, noexec, noexec, noexec, noexec, noexec)
zpnorm(xr2zpbkc1, noexec, noexec, noexec, noexec, noexec, noexec, exec, noexec)
zpnorm(xr2zpbkcm1, noexec, noexec, noexec, noexec, noexec, noexec, noexec, exec)
zpnorm(xr2zpebk, noexec, exec, noexec, noexec, noexec, noexec, noexec, noexec)
zpnorm(xr2zpebkc1, noexec, exec, noexec, noexec, noexec, noexec, exec, noexec)
zpnorm(xr2zpebkcm1, noexec, exec, noexec, noexec, noexec, noexec, noexec, exec)
zpnorm(xr2zpcbk, noexec, noexec, exec, noexec, noexec, noexec, noexec, noexec)
zpnorm(xr2zpecbk, noexec, exec, exec, noexec, noexec, noexec, noexec, noexec)
zpnorm(xi2zpbk, exec, noexec, noexec, noexec, noexec, noexec, noexec, noexec)
zpnorm(xi2zpbkc1, exec, noexec, noexec, noexec, noexec, noexec, exec, noexec)
zpnorm(xi2zpbkcm1, exec, noexec, noexec, noexec, noexec, noexec, noexec, exec)
zpnorm(xi2zpebk, exec, exec, noexec, noexec, noexec, noexec, noexec, noexec)
zpnorm(xi2zpebkc1, exec, exec, noexec, noexec, noexec, noexec, exec, noexec)
zpnorm(xi2zpebkcm1, exec, exec, noexec, noexec, noexec, noexec, noexec, exec)
zpnorm(xi2zpcbk, exec, noexec, exec, noexec, noexec, noexec, noexec, noexec)
zpnorm(xi2zpecbk, exec, exec, exec, noexec, noexec, noexec, noexec, noexec)

